#!/usr/bin/env python3
import os
import sys
import helpers
from termcolor import colored
from analyzer import Analyzer


if len(sys.argv) != 2:
    sys.exit('Usage: ./tweet @screen_name')
    
positives = os.path.join(sys.path[0], "positive-words.txt")
negatives = os.path.join(sys.path[0], "negative-words.txt")

# instantiate analyzer
analyzer = Analyzer(positives, negatives)

name = sys.argv[1].lstrip('@')
tweets = helpers.get_user_timeline(name, 100)
if tweets == None:
    sys.exit(colored("Unexpected error!", "red"))
for tweet in tweets:
    score = analyzer.analyze(tweet)
    if score > 0.0:
        print(colored(score, "green"), end=" ")
        print(colored(tweet, "green"))
    elif score < 0.0:
        print(colored(score, "red"), end=" ")
        print(colored(tweet, "red"))
    else:
        print(colored(score, "yellow"), end=" ")
        print(colored(tweet, "yellow"))
